// Autogenerated from AddressStorageABI.json
// Exported as TypeScript module to avoid JSON imports in frontend
const abi = 
[
  {
    "inputs": [],
    "name": "InvalidAddress",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NoStoredAddressFound",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "user",
        "type": "address"
      }
    ],
    "name": "AddressStored",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "userA",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "userB",
        "type": "address"
      }
    ],
    "name": "compareAddresses",
    "outputs": [
      {
        "internalType": "eaddress",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getStoredAddress",
    "outputs": [
      {
        "internalType": "eaddress",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "user",
        "type": "address"
      }
    ],
    "name": "getStoredAddressByUser",
    "outputs": [
      {
        "internalType": "eaddress",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "externalEaddress",
        "name": "inputAddress",
        "type": "bytes32"
      },
      {
        "internalType": "bytes",
        "name": "inputProof",
        "type": "bytes"
      }
    ],
    "name": "storeAddress",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "storeRandomAddress",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
];

export default abi as const;
